### PR TITLE
Version change to 0.1.0

### PR DESCRIPTION
**Pull request by krishnaIndia**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/86)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[CHANGELOG.md, line 1 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/86#-JsZD-PFP8bhRVSV4Ufv)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/928f1146d3a8030f78c75ba983f132f4f41f86a1/CHANGELOG.md#L1)):</sup>
prefix two `##` maybe

---

<sup>**[CHANGELOG.md, line 3 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/86#-JsZCxNWxoJ6W6OPyxm3)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/928f1146d3a8030f78c75ba983f132f4f41f86a1/CHANGELOG.md#L3)):</sup>
prefix three `###` maybe

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/86)

**Comment by ustulation** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/86)

**Comment by Viv-Rajkumar** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/86)

**Pull request merged**
