### PR TITLE
Maid 1099 unit tests

### PR DESCRIPTION
**Pull request by krishnaIndia**
Unit tests for APi added. User Metadata for container has been suppressed. User Metadata can only be added for blobs

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/61)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by krishnaIndia** [comment]
Build fails because of the changes in RoutingClient in routing library

**Comment by rossmuir** [comment]
test this please

**Comment by krishnaIndia** [comment]
New PR raised

**Pull request closed without merging**
