### PR TITLE
Maid 1082 file helper

### PR DESCRIPTION
**Pull request by krishnaIndia**
FileHelper implemented with create, update and update_user_metadata functions.
Implemented the network operations like get and put in NetworkStorage and this can be used for performing network operations over the MaidSafe network. This approach gives flexibility to share the NetworkStorage instance easily rather than sharing &mut client. If this approach is fine, then the DirectoryHeper can be re-factored.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/34)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
r? @krishnaIndia 
reverting back to you for Interface Changes

**Comment by krishnaIndia** [comment]
r? @ustulation
Implemented the interface changes and put response handling

**Comment by ustulation** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks pending.
Reviewed files:
- .gitignore @ r1
- README.md @ r3
- src/client/mod.rs @ r8
- src/nfs/helper/directory_helper.rs @ r5
- src/nfs/helper/file_helper.rs @ r4
- src/nfs/helper/mod.rs @ r1
- src/nfs/io/mod.rs @ r1
- src/nfs/io/network_storage.rs @ r2
- src/nfs/io/writer.rs @ r4
- src/nfs/mod.rs @ r1
- src/nfs/types/directory_listing.rs @ r1
- src/nfs/types/file.rs @ r1
- src/nfs/types/metadata.rs @ r1

---

<sup>**[src/nfs/types/metadata.rs, line 66 \[r8\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/34#-Jqn5_PLMwZFTIchK-Xs)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/c8795fa8a47f2d410d00088f873a1e3e224df3af/src/nfs/types/metadata.rs#L66)):</sup>
Rust idiom is avoid `return` whenever you can. So maybe `if condition { Some(stuff) } else { None }` (of-course not in a single line) is better

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/34)

**Comment by ustulation** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks pending.
Reviewed files:
- src/nfs/types/metadata.rs @ r9

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/34)

**Pull request merged**
