### PR TITLE
Maid 1232 test versioned

### PR DESCRIPTION
**Pull request by krishnaIndia**
MAID-1225, MAID-1227, MAID-1232

Client test cases and structured data test cases integarted

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/111)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 32 unresolved discussions, some commit checks failed.

---

<sup>**[examples/self_authentication.rs, line 22 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufoDtgDQAUjI9HQVui)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/examples/self_authentication.rs#L22)):</sup>
why is this commented .. it was working .

---

<sup>**[src/client/mod.rs, line 363 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufoRV9PBiGolB6iLzC)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/client/mod.rs#L363)):</sup>
why is this commented out. It is working in master.

---

<sup>**[src/lib.rs, line 71 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufonYsoZoWDscJsT6t)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/lib.rs#L71)):</sup>
arrange in pyramid style ie., above `pub mod structured_data_operations;`

---

<sup>**[src/lib.rs, line 73 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufovLLRF6R-i3osk3y)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/lib.rs#L73)):</sup>
no need for `self::` i think as this is `lib.rs`

---

<sup>**[src/self_encryption_storage.rs, line 35 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufpHx0tXSOL0dlJ0pc)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/self_encryption_storage.rs#L35)):</sup>
gap after `;`

---

<sup>**[src/self_encryption_storage.rs, line 38 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufpbXpA2mSglFbMjpp)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/self_encryption_storage.rs#L38)):</sup>
why not `name[i]` ?

---

<sup>**[src/self_encryption_storage.rs, line 40 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufpnyw_wTUU_sVT_5N)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/self_encryption_storage.rs#L40)):</sup>
this is not a mutex. It is an `Arc`. Anyway why is cloning required ?

---

<sup>**[src/self_encryption_storage.rs, line 41 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufq6FlWr-DIU5HknLs)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/self_encryption_storage.rs#L41)):</sup>
This is client mutex (what you get after `unwrap()`)

---

<sup>**[src/self_encryption_storage.rs, line 60 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufqmPdPZgHqc5xdsSv)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/self_encryption_storage.rs#L60)):</sup>
why cloning ? And again this is not a mutex.

---

<sup>**[src/self_encryption_storage.rs, line 61 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufqrgNdvjQdlGhF_hn)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/self_encryption_storage.rs#L61)):</sup>
This is a mutex (if you want to name it `client_mutex`)

---

<sup>**[src/structured_data_operations/mod.rs, line 59 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufrarqaD_vLUmD1UB1)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L59)):</sup>
try:
`structured_data.replace_signatures(vec![::sodiumoxide::crypto::sign::Signature([::std::u8::MAX; ::sodiumoxide::crypto::sign::SIGNATUREBYTES]); max_signatures_possible)`
OR
`sturctured_data.replace_signatures((0..max_signatures_possible).iter().map(|_| fake_signature.clone()).collect::Vec<_>());`

---

<sup>**[src/structured_data_operations/mod.rs, line 63 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufsP27becFvrErQz4P)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L63)):</sup>
use `try!()` and return `Result<usize, ::error::ClientError)`
No unwraps anywhere except mutexs.

---

<sup>**[src/structured_data_operations/mod.rs, line 94 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufspquv9zWmMM8dgUF)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L94)):</sup>
make a comment `//` not a documentation

---

<sup>**[src/structured_data_operations/mod.rs, line 95 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufsx-RwOgAsXTMeiS7)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L95)):</sup>
No gap before `:`

---

<sup>**[src/structured_data_operations/mod.rs, line 96 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufsspJodHSvPsCnPeC)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L96)):</sup>
make a comment `//`

---

<sup>**[src/structured_data_operations/mod.rs, line 105 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JuftCALFDKpNtSV7jne)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L105)):</sup>
`get_max_sized_public_keys` seems to be a better name as you are not generating them, just putting in max value.

---

<sup>**[src/structured_data_operations/mod.rs, line 130 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JuftlBojJBJXZlmtqEX)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L130)):</sup>
`Vec::new()` is semantically better instead of `vec![1u8; 0]`

---

<sup>**[src/structured_data_operations/mod.rs, line 134 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JuftxFvGbA2tNMfdMmX)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L134)):</sup>
`Vec::new()`

---

<sup>**[src/structured_data_operations/unversioned.rs, line 60 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufuqr5_zg3dJK2I9Ge)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/unversioned.rs#L60)):</sup>
remove

---

<sup>**[src/structured_data_operations/unversioned.rs, line 71 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufutJyviIrVCtSIm45)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/unversioned.rs#L71)):</sup>
remove

---

<sup>**[src/structured_data_operations/unversioned.rs, line 131 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufxfCL8zvIb5CfC_Id)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/unversioned.rs#L131)):</sup>
no `ref` required

---

<sup>**[src/structured_data_operations/unversioned.rs, line 138 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufwj-n43ifJwygBTdK)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/unversioned.rs#L138)):</sup>
while at it change this to `&Vec<u8>` then below do:
```
let data: _;
let data_to_serialise = if let Some........ {
    data = try!(.....);
    &data
else {
    raw_data
}
```

---

<sup>**[src/structured_data_operations/unversioned.rs, line 142 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufxiKevzVlduoyFh9m)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/unversioned.rs#L142)):</sup>
no `ref` required. Make sure you pull in my changes. These were all addressed there.

---

<sup>**[src/structured_data_operations/versioned.rs, line 106 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufw8Y_Ei8ZsjVPs9F_)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/versioned.rs#L106)):</sup>
no gap should be there before `:`

---

<sup>**[src/utility/test_utils.rs, line 22 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufyAVA8G2vQ_ulJTK4)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L22)):</sup>
no `unwraps` anywhere please. All `try!()'s`

---

<sup>**[src/utility/test_utils.rs, line 23 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufyiho5tyyNMHNsy5T)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L23)):</sup>
gap after function

---

<sup>**[src/utility/test_utils.rs, line 31 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufyi7bPcPmb54R8VnK)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L31)):</sup>
gap after function

---

<sup>**[src/utility/test_utils.rs, line 33 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufyQkX7I5qoP0kjXML)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L33)):</sup>
rename to `get_max_sized_public_keys(...)`

---

<sup>**[src/utility/test_utils.rs, line 39 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufyfrFPbUTssF1o7Vl)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L39)):</sup>
gap after function

---

<sup>**[src/utility/test_utils.rs, line 41 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufyZHT3vB-Odbzr-qf)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L41)):</sup>
rename to `get_max_sized_secret_keys`

---

<sup>**[src/utility/test_utils.rs, line 47 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufydu4HpdS63tEFT2C)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L47)):</sup>
gap after function

---

<sup>**[src/utility/test_utils.rs, line 55 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufym6sRIV5b25Cv0oV)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L55)):</sup>
gap after function

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111)

**Comment by krishnaIndia** [comment]
Review status: 5 of 10 files reviewed at latest revision, 32 unresolved discussions, some commit checks failed.

---

<sup>**[src/lib.rs, line 71 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufonYsoZoWDscJsT6t)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/lib.rs#L71)):</sup>
Done.

---

<sup>**[src/lib.rs, line 73 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufovLLRF6R-i3osk3y)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/lib.rs#L73)):</sup>
Done.

---

<sup>**[src/self_encryption_storage.rs, line 35 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufpHx0tXSOL0dlJ0pc)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/self_encryption_storage.rs#L35)):</sup>
Done.

---

<sup>**[src/self_encryption_storage.rs, line 38 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufpbXpA2mSglFbMjpp)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/self_encryption_storage.rs#L38)):</sup>
Done.

---

<sup>**[src/self_encryption_storage.rs, line 40 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufpnyw_wTUU_sVT_5N)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/self_encryption_storage.rs#L40)):</sup>
Done.

---

<sup>**[src/self_encryption_storage.rs, line 41 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufq6FlWr-DIU5HknLs)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/self_encryption_storage.rs#L41)):</sup>
Done.

---

<sup>**[src/self_encryption_storage.rs, line 60 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufqmPdPZgHqc5xdsSv)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/self_encryption_storage.rs#L60)):</sup>
Done.

---

<sup>**[src/self_encryption_storage.rs, line 61 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufqrgNdvjQdlGhF_hn)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/self_encryption_storage.rs#L61)):</sup>
Done.

---

<sup>**[src/structured_data_operations/mod.rs, line 59 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufrarqaD_vLUmD1UB1)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L59)):</sup>
Done.

---

<sup>**[src/structured_data_operations/mod.rs, line 63 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufsP27becFvrErQz4P)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L63)):</sup>
Done.

---

<sup>**[src/structured_data_operations/mod.rs, line 94 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufspquv9zWmMM8dgUF)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L94)):</sup>
Done.

---

<sup>**[src/structured_data_operations/mod.rs, line 95 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufsx-RwOgAsXTMeiS7)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L95)):</sup>
Done.

---

<sup>**[src/structured_data_operations/mod.rs, line 96 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufsspJodHSvPsCnPeC)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L96)):</sup>
Done.

---

<sup>**[src/structured_data_operations/mod.rs, line 105 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JuftCALFDKpNtSV7jne)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L105)):</sup>
Done.

---

<sup>**[src/structured_data_operations/mod.rs, line 130 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JuftlBojJBJXZlmtqEX)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L130)):</sup>
Done.

---

<sup>**[src/structured_data_operations/mod.rs, line 134 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JuftxFvGbA2tNMfdMmX)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/mod.rs#L134)):</sup>
Done.

---

<sup>**[src/structured_data_operations/unversioned.rs, line 60 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufuqr5_zg3dJK2I9Ge)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/unversioned.rs#L60)):</sup>
Done.

---

<sup>**[src/structured_data_operations/unversioned.rs, line 71 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufutJyviIrVCtSIm45)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/unversioned.rs#L71)):</sup>
Done.

---

<sup>**[src/structured_data_operations/unversioned.rs, line 131 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufxfCL8zvIb5CfC_Id)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/unversioned.rs#L131)):</sup>
Done.

---

<sup>**[src/structured_data_operations/unversioned.rs, line 138 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufwj-n43ifJwygBTdK)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/unversioned.rs#L138)):</sup>
Done.

---

<sup>**[src/structured_data_operations/unversioned.rs, line 142 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufxiKevzVlduoyFh9m)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/unversioned.rs#L142)):</sup>
Done.

---

<sup>**[src/structured_data_operations/versioned.rs, line 106 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufw8Y_Ei8ZsjVPs9F_)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/structured_data_operations/versioned.rs#L106)):</sup>
Done.

---

<sup>**[src/utility/test_utils.rs, line 22 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufyAVA8G2vQ_ulJTK4)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L22)):</sup>
Done. match used instead, if the client is not initialised, then the test can not pass, thus a panic is called in the utility function itself

---

<sup>**[src/utility/test_utils.rs, line 23 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufyiho5tyyNMHNsy5T)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L23)):</sup>
Done.

---

<sup>**[src/utility/test_utils.rs, line 31 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufyi7bPcPmb54R8VnK)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L31)):</sup>
Done.

---

<sup>**[src/utility/test_utils.rs, line 33 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufyQkX7I5qoP0kjXML)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L33)):</sup>
Done.

---

<sup>**[src/utility/test_utils.rs, line 39 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufyfrFPbUTssF1o7Vl)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L39)):</sup>
Done.

---

<sup>**[src/utility/test_utils.rs, line 41 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufyZHT3vB-Odbzr-qf)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L41)):</sup>
Done.

---

<sup>**[src/utility/test_utils.rs, line 47 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufydu4HpdS63tEFT2C)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L47)):</sup>
Done.

---

<sup>**[src/utility/test_utils.rs, line 55 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-Jufym6sRIV5b25Cv0oV)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/utility/test_utils.rs#L55)):</sup>
Done.

---

<sup>**[examples/self_authentication.rs, line 22 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufoDtgDQAUjI9HQVui)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/examples/self_authentication.rs#L22)):</sup>
Done.

---

<sup>**[src/client/mod.rs, line 363 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111#-JufoRV9PBiGolB6iLzC)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/5f01a958509f731a9db7cfdfbe91bb7b631dedae/src/client/mod.rs#L363)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111)

**Comment by krishnaIndia** [comment]
Thanks for the detailed review. Implemented the changes suggested

**Comment by ustulation** [comment]
Reviewed 3 of 7 files at r3.
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111)

**Comment by ustulation** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/111)

**Pull request merged**
