### PR TITLE
Maid 1252

### PR DESCRIPTION
**Pull request by ustulation**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/101)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @krishnaIndia

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by krishnaIndia** [comment]
<sup>**[src/client/non_networking_test_framework/mod.rs, line 179 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/101#-JtsvV9H1JH1Z3l2nK4G)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6858fa4dbc6f612b5e2d0a8c82001817256fcd90/src/client/non_networking_test_framework/mod.rs#L179)):</sup>
Should we add delete fn also?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/101)

**Comment by krishnaIndia** [comment]
<sup>**[src/client/mock_routing_types.rs, line 138 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/101#-JtsvpxVcMNUVf5QWO7x)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6858fa4dbc6f612b5e2d0a8c82001817256fcd90/src/client/mock_routing_types.rs#L138)):</sup>
If we are using the maidsafe_sodiumoxide then custom implementation can be removed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/101)

**Comment by krishnaIndia** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/101)

**Comment by ustulation** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[src/client/mock_routing_types.rs, line 138 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/101#-JtsvpxVcMNUVf5QWO7x)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6858fa4dbc6f612b5e2d0a8c82001817256fcd90/src/client/mock_routing_types.rs#L138)):</sup>
This is a throw away code once the routing is stabilized. So it is only till then.

---

<sup>**[src/client/non_networking_test_framework/mod.rs, line 179 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/101#-JtsvV9H1JH1Z3l2nK4G)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6858fa4dbc6f612b5e2d0a8c82001817256fcd90/src/client/non_networking_test_framework/mod.rs#L179)):</sup>
nice one :) .. It is an important one.. Done and tested thoroughly now. Pls check the test cases.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/101)

**Pull request merged**
