### PR TITLE
Maid-1078-create-account-and-initial-non-blocking-design

### PR DESCRIPTION
**Pull request by ustulation**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/32)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @krishnaIndia

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by benjaminbollen** [comment]
https://github.com/maidsafe/routing/issues/277

**Comment by krishnaIndia** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- src/account.rs @ r1
- src/client.rs @ r1
- src/client/callback_interface.rs @ r1
- src/client/mod.rs @ r3
- src/client/user_account.rs @ r2
- src/lib.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/32)

**Comment by dirvine** [comment]
r? @dirvine

---

Review status: all files reviewed, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/32)

**Comment by dirvine** [comment]
Interesting approach, looks like Vaults themselves could do similar now we see they also require access to routing in some methods as well. Can you please discuss this with Qi

---

Review status: all files reviewed, 8 unresolved discussions, some commit checks failed.
Reviewed files:
- src/account.rs @ r1
- src/client.rs @ r1
- src/client/callback_interface.rs @ r1
- src/client/mod.rs @ r3
- src/client/user_account.rs @ r2
- src/lib.rs @ r1

---

<sup>**[src/client/callback_interface.rs, line 19 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/32#-JqQAkKeYohMVjbzcb3r)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/89279eb8233db7edb18f435f78b12796c67f3aaa/src/client/callback_interface.rs#L19)):</sup>
this is updated in crates so perhaps Cargo.toml needs a tweak as well if we want the latest version.

---

<sup>**[src/client/callback_interface.rs, line 29 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/32#-JqQA5_PZnaJPnE9zL9C)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/89279eb8233db7edb18f435f78b12796c67f3aaa/src/client/callback_interface.rs#L29)):</sup>
We should remove these comments (happy in next PR)

---

<sup>**[src/client/mod.rs, line 114 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/32#-JqQB14xxCT8drfgEiHo)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/89279eb8233db7edb18f435f78b12796c67f3aaa/src/client/mod.rs#L114)):</sup>
OK I assume this is a separate task now. 

---

<sup>**[src/client/mod.rs, line 160 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/32#-JqQBFyCpEB6KmagyDX2)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/89279eb8233db7edb18f435f78b12796c67f3aaa/src/client/mod.rs#L160)):</sup>
Worth documenting these as we go especially introducing Async parts like WaitCondition 

---

<sup>**[src/client/user_account.rs, line 62 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/32#-JqQBSQddbTm4zbTLd47)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/89279eb8233db7edb18f435f78b12796c67f3aaa/src/client/user_account.rs#L62)):</sup>
Types will change this slightly now, so will require an update @s-brian can explain, but some nice docs coming very soon to let you see clearly how types has evolved. 

---

<sup>**[src/client/user_account.rs, line 125 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/32#-JqQDAa1h_saNNMZIiuR)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/89279eb8233db7edb18f435f78b12796c67f3aaa/src/client/user_account.rs#L125)):</sup>
I presume this generate_crypto_keys is the PBKDFII function

---

<sup>**[src/client/user_account.rs, line 130 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/32#-JqQCxLraP6CcMIzAXfS)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/89279eb8233db7edb18f435f78b12796c67f3aaa/src/client/user_account.rs#L130)):</sup>
We should have a task for authenticated encrypt here for sure. This is available in sodium and also rust-crypto I believe (as GCM mode AES)

---

<sup>**[src/client/user_account.rs, line 135 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/32#-JqQDOni0IhSNyhX2Uth)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/89279eb8233db7edb18f435f78b12796c67f3aaa/src/client/user_account.rs#L135)):</sup>
Yes cbc not best here, gcm recommended.  Please make a task for this.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/32)

**Pull request merged**
