### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by krishnaIndia**
Refactor of NFS module

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/51)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Review status: all files reviewed, 4 unresolved discussions, some commit checks failed.
Reviewed files:
- README.md @ r1
- src/nfs/directory_info.rs @ r1
- src/nfs/directory_listing.rs @ r1
- src/nfs/file.rs @ r1
- src/nfs/helper/directory_helper.rs @ r1
- src/nfs/helper/file_helper.rs @ r1
- src/nfs/helper/mod.rs @ r1
- src/nfs/io/network_storage.rs @ r1
- src/nfs/io/reader.rs @ r1
- src/nfs/io/writer.rs @ r1
- src/nfs/metadata.rs @ r1
- src/nfs/mod.rs @ r1
- src/nfs/rest/blob.rs @ r1
- src/nfs/rest/container.rs @ r1
- src/nfs/rest/container_info.rs @ r1
- src/nfs/traits/mod.rs @ r1
- src/nfs/traits/wrapper.rs @ r1

---

<sup>**[src/nfs/helper/mod.rs, line 20 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51#-JrGqtTeafovk6qQoIqT)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6f4f0f4f468c3e30fdbdaa71eae19a5608a7b0c9/src/nfs/helper/mod.rs#L20)):</sup>
remove ??

---

<sup>**[src/nfs/io/writer.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51#-JrGr0zDbNBqmRacdqSp)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6f4f0f4f468c3e30fdbdaa71eae19a5608a7b0c9/src/nfs/io/writer.rs#L44)):</sup>
trailing spaces

---

<sup>**[src/nfs/io/writer.rs, line 57 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51#-JrGrC-zQUbdwJ01EabS)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6f4f0f4f468c3e30fdbdaa71eae19a5608a7b0c9/src/nfs/io/writer.rs#L57)):</sup>
what is upsert ?

---

<sup>**[src/nfs/metadata.rs, line 56 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51#-JrGrOWtRDnsCE5IbM7f)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6f4f0f4f468c3e30fdbdaa71eae19a5608a7b0c9/src/nfs/metadata.rs#L56)):</sup>
unnecessary NOT operator - just reverse `if` and `else` without `!` operator

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51)

**Comment by krishnaIndia** [comment]
Review status: all files reviewed, 4 unresolved discussions, some commit checks failed.

---

<sup>**[src/nfs/io/writer.rs, line 57 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51#-JrGrC-zQUbdwJ01EabS)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6f4f0f4f468c3e30fdbdaa71eae19a5608a7b0c9/src/nfs/io/writer.rs#L57)):</sup>
Update or insert = Upsert.  This function would update if the file exists or insert if the file is new 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51)

**Comment by krishnaIndia** [comment]
Review status: all files reviewed, 3 unresolved discussions, some commit checks failed.

---

<sup>**[src/nfs/helper/mod.rs, line 20 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51#-JrGqtTeafovk6qQoIqT)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6f4f0f4f468c3e30fdbdaa71eae19a5608a7b0c9/src/nfs/helper/mod.rs#L20)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51)

**Comment by krishnaIndia** [comment]
Review status: all files reviewed, 3 unresolved discussions, some commit checks failed.

---

<sup>**[src/nfs/io/writer.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51#-JrGr0zDbNBqmRacdqSp)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6f4f0f4f468c3e30fdbdaa71eae19a5608a7b0c9/src/nfs/io/writer.rs#L44)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51)

**Comment by krishnaIndia** [comment]
Review status: all files reviewed, 3 unresolved discussions, some commit checks failed.

---

<sup>**[src/nfs/metadata.rs, line 56 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51#-JrGrOWtRDnsCE5IbM7f)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6f4f0f4f468c3e30fdbdaa71eae19a5608a7b0c9/src/nfs/metadata.rs#L56)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51)

**Comment by ustulation** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- src/nfs/helper/mod.rs @ r2
- src/nfs/io/writer.rs @ r2
- src/nfs/metadata.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/51)

**Pull request merged**
