### PR TITLE
Travis integration

### PR DESCRIPTION
**Pull request by krishnaIndia**
Travis integration for document generation and version tagging

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/80)

### CODE REVIEW

**Comment by Viv-Rajkumar** [comment]
Reviewed 2 of 2 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[README.md, line 11 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/80#-JsA654hsE-X1RRqtm35)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/cb96114a161f840c6b471b35fd8e336e1967a014/README.md#L11)):</sup>
shouldn't the url for Master branch docs be `http://maidsafe.github.io/maidsafe_client/master` ?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/80)

**Comment by krishnaIndia** [comment]
<sup>**[README.md, line 11 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/80#-JsA654hsE-X1RRqtm35)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/cb96114a161f840c6b471b35fd8e336e1967a014/README.md#L11)):</sup>
it would auto redirect to master by default

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/80)

**Comment by Viv-Rajkumar** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/80)

**Pull request merged**
