### PR TITLE
MAID-1223, MAID-1234, MAID-1228, MAID-1222

### PR DESCRIPTION
**Pull request by ustulation**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/104)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @krishnaIndia

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by krishnaIndia** [comment]
<sup>**[src/structured_data_operations/unversioned.rs, line 78 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/104#-JuAC0Xz4hqNXv94UKlr)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/d9f79880eff5adc447911105c9f4f437581b5745/src/structured_data_operations/unversioned.rs#L78)):</sup>
Here we are always doing a put operation. Can we call put or post based on the version number? 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/104)

**Comment by krishnaIndia** [comment]
Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/104)

**Comment by krishnaIndia** [comment]
<sup>**[src/structured_data_operations/unversioned.rs, line 78 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/104#-JuAC0Xz4hqNXv94UKlr)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/d9f79880eff5adc447911105c9f4f437581b5745/src/structured_data_operations/unversioned.rs#L78)):</sup>
Hey Sorry, my mistake it is put on an immutable data, which is legit. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/104)

**Comment by krishnaIndia** [comment]
Reviewed 2 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/104)

**Comment by krishnaIndia** [comment]
Nice One!

**Pull request merged**
