### PR TITLE
some warning fixes

### PR DESCRIPTION
**Pull request by mmoadeli**
The legitimate warnings were not suppressed.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/57)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @ustulation (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way Github handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by ustulation** [comment]
Nice work @mmoadeli  :) .. But the warning specially in client/mod.rs is due to certain variables not being used .. this is because of mock_routing background that client is talking to right now. When actual routing is integrated some of these will no longer be a warning,  but if presently if i accept your PR and change these variable names to `_` then it would be some re-work to put those names back once the actual routing is integrated. So these warnings are known and sort of left deliberately. Let me know if you want to discuss this further or have other ideas. Thanks !!

**Comment by mmoadeli** [comment]
cool Spandan. I believed that some one with more exposure has to deal with issues like this.

**Comment by ustulation** [comment]
nw, so it is ok if i close this PR @mmoadeli ?

**Comment by dirvine** [comment]
I would go for closing @ustulation

**Pull request closed without merging**
