### PR TITLE
Maid 1098 update blob

### PR DESCRIPTION
**Pull request by krishnaIndia**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/55)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks pending.
Reviewed files:
- README.md @ r1
- src/nfs/rest/blob.rs @ r1
- src/nfs/rest/container.rs @ r1
- src/nfs/rest/container_info.rs @ r1

---

<sup>**[src/nfs/rest/blob.rs, line 65 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/55#-JrI2Ys7A_MgTr8fzgfr)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6134a5078ee65047e7a96ca23bd8cb969d202982/src/nfs/rest/blob.rs#L65)):</sup>
trailing space

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/55)

**Comment by krishnaIndia** [comment]
Review status: 3 of 4 files reviewed, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/nfs/rest/blob.rs, line 65 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/55#-JrI2Ys7A_MgTr8fzgfr)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/6134a5078ee65047e7a96ca23bd8cb969d202982/src/nfs/rest/blob.rs#L65)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/55)

**Comment by ustulation** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- src/nfs/rest/blob.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/55)

**Pull request merged**
