### PR TITLE
Maid 1081 directory helper

### PR DESCRIPTION
**Pull request by krishnaIndia**
Removed ContainerId data type, and replaced with NameType. Renamed ContainerInfo to DirectoryInfo to maintain consistency in naming.

Implemented DirectoryHelper.

1. FIXME marker is present in create fn of DirectoryHelper. 
 The owner for the Structured data has to be passed. That can be done once the account creation is implemented.
2. StructuredData type are using the versions in  Vec<Vec<NameType>> format, and not the updated design. Should refactor the version implementation once the maidsafe_types crate is updated

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/31)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Review status: 2 of 10 files reviewed, 1 unresolved discussion, some commit checks failed.

---

<sup>**[src/nfs/helper/directory_helper.rs, line 59 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31#-JqJRKWLJciRTT2od9gH)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/e84c6723c8902c4722013e229bcc959100311f0b/src/nfs/helper/directory_helper.rs#L59)):</sup>
Structured data has changed .. with new signature it is just vec<NameType>

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31)

**Comment by ustulation** [comment]
Review status: 3 of 10 files reviewed, 2 unresolved discussions, some commit checks failed.
Reviewed files:
- README.md @ r1
- src/lib.rs @ r1
- src/nfs/helper/directory_helper.rs @ r1

---

<sup>**[src/nfs/helper/directory_helper.rs, line 66 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31#-JqJS5RJghvrYodpFxfz)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/e84c6723c8902c4722013e229bcc959100311f0b/src/nfs/helper/directory_helper.rs#L66)):</sup>
this will be blocking call .. I think major change is in order because all these will be blocking call on a single instance of Client whereas the Client is perfectly capable of non-blocking operations. So not reviewing further change as this whole design should change

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31)

**Comment by krishnaIndia** [comment]
Implementation updated to support the design change in the Client.

**Comment by ustulation** [comment]
Review status: 1 of 12 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/client/mod.rs, line 154 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31#-JqT4m_u9X6Bkr_LdBKB)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/02270885d29ff4580984f9a71f2d7059a44c2647/src/client/mod.rs#L154)):</sup>
should be same signature as get below .. otherwise there would be no way to handle put_response if required later.

---

<sup>**[src/nfs/helper/directory_helper.rs, line 142 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31#-JqT5wDxGAKGY6VMRyeA)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/02270885d29ff4580984f9a71f2d7059a44c2647/src/nfs/helper/directory_helper.rs#L142)):</sup>
This is delegating to a different function ..  but still blocking ... please check create_account in client.rs to see how to do this in a separate thread - only thing blocking should be login and register .. rest all non-blocking .. If it is to be refactored later i can accept this blocking call for now.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31)

**Comment by krishnaIndia** [comment]
Review status: 1 of 12 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/nfs/helper/directory_helper.rs, line 57 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31#-JqJRKWLJciRTT2od9gH)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/e84c6723c8902c4722013e229bcc959100311f0b/src/nfs/helper/directory_helper.rs#L57)):</sup>
It is just a vector and it matches the signature of the StructuredData of maidsafe_types(1.0.4)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31)

**Comment by krishnaIndia** [comment]
Review status: 1 of 12 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/nfs/helper/directory_helper.rs, line 142 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31#-JqT5wDxGAKGY6VMRyeA)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/02270885d29ff4580984f9a71f2d7059a44c2647/src/nfs/helper/directory_helper.rs#L142)):</sup>
Not able to find a client.rs file.  DirectoryHelper is a short lived instance and mostly created to perform single operation. The upper layer like REST or POSIX should be managing it asynchronously/Synchronously. If I am wrong then, I will refactor along with the next task.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31)

**Comment by krishnaIndia** [comment]
Review status: 1 of 11 files reviewed, 3 unresolved discussions, some commit checks pending.

---

<sup>**[src/client/mod.rs, line 154 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31#-JqT4m_u9X6Bkr_LdBKB)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/02270885d29ff4580984f9a71f2d7059a44c2647/src/client/mod.rs#L154)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31)

**Comment by ustulation** [comment]
Review status: 1 of 11 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/nfs/helper/directory_helper.rs, line 59 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31#-JqJRKWLJciRTT2od9gH)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/e84c6723c8902c4722013e229bcc959100311f0b/src/nfs/helper/directory_helper.rs#L59)):</sup>
that was an old comment on previous diff

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31)

**Comment by ustulation** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- src/client/mod.rs @ r3
- src/nfs/helper/directory_helper.rs @ r2
- src/nfs/helper/mod.rs @ r1
- src/nfs/mod.rs @ r1
- src/nfs/types/container_id.rs @ r1
- src/nfs/types/container_info.rs @ r1
- src/nfs/types/directory_info.rs @ r2
- src/nfs/types/directory_listing.rs @ r2
- src/nfs/types/file.rs @ r2
- src/nfs/types/mod.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/31)

**Pull request merged**
