### PR TITLE
MAID-1219_Ids moved from maidsafe_types

### PR DESCRIPTION
**Pull request by krishnaIndia**
Private and public IDs moved from maidsafe_types. Had to remove unsafe_code lint check because the #[allow(unsafe_code)] wont work in macros.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/100)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Major Points:
<1> Need to remove Sendable trait.
<2> Shouldn't contain type-tag. Use `pub const` for cbor-tagging.
<3> Serialisation and deserialisation need to change to not require Parser as we are not storing these on the network any more (eg., No PublicMaid). - Please confirm from @dirvine first whether we are removing unauthorised-PUT in this sprint, otherwise this point is not valid.

**Comment by krishnaIndia** [comment]
Sendable trait and parser for Id types has been removed.

**Comment by ustulation** [comment]
Reviewed 1 of 8 files at r1, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[src/client/mod.rs, line 111 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju6-Su_ofcd0bNQosFi)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/client/mod.rs#L111)):</sup>
trailing spaces

---

<sup>**[src/id/id_type.rs, line 26 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju60eK16T92LU3EumbW)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/id/id_type.rs#L26)):</sup>
1 gap after line

---

<sup>**[src/id/id_type.rs, line 45 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju6-hU0TKSaitq0DUd1)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/id/id_type.rs#L45)):</sup>
should be a gap after line .. same for the rest

---

<sup>**[src/id/id_type.rs, line 77 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju6-ou22oqxdnVS7-st)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/id/id_type.rs#L77)):</sup>
`pub fn open(1st param,`

---

<sup>**[src/id/revocation_id_type.rs, line 29 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju60YHZVSoJ5FhK1nYA)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/id/revocation_id_type.rs#L29)):</sup>
1 gap after line

---

<sup>**[src/id/revocation_id_type.rs, line 116 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju60LSUaZe4aQ_JTKyn)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/id/revocation_id_type.rs#L116)):</sup>
gap between function close and arrow and between arrow and return type.
For all below too

---

<sup>**[src/macros.rs, line 28 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju60E4FvRYd7AAY8NDt)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/macros.rs#L28)):</sup>
1 gap after line

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100)

**Comment by krishnaIndia** [comment]
Review status: 4 of 10 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

<sup>**[src/client/mod.rs, line 111 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju6-Su_ofcd0bNQosFi)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/client/mod.rs#L111)):</sup>
Done.

---

<sup>**[src/id/id_type.rs, line 26 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju60eK16T92LU3EumbW)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/id/id_type.rs#L26)):</sup>
Done.

---

<sup>**[src/id/id_type.rs, line 45 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju6-hU0TKSaitq0DUd1)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/id/id_type.rs#L45)):</sup>
Done.

---

<sup>**[src/id/id_type.rs, line 77 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju6-ou22oqxdnVS7-st)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/id/id_type.rs#L77)):</sup>
Done.

---

<sup>**[src/id/revocation_id_type.rs, line 29 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju60YHZVSoJ5FhK1nYA)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/id/revocation_id_type.rs#L29)):</sup>
Done.

---

<sup>**[src/id/revocation_id_type.rs, line 116 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju60LSUaZe4aQ_JTKyn)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/id/revocation_id_type.rs#L116)):</sup>
Done.

---

<sup>**[src/macros.rs, line 28 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju60E4FvRYd7AAY8NDt)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/macros.rs#L28)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100)

**Comment by ustulation** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[src/id/revocation_id_type.rs, line 116 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju60LSUaZe4aQ_JTKyn)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/id/revocation_id_type.rs#L116)):</sup>
still not done .. pls check: should be
`fn encode<E: ::rustc_serialize::Encoder>(&self, e: &mut E) -> Result<(), E::Error> {`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100)

**Comment by krishnaIndia** [comment]
<sup>**[src/id/revocation_id_type.rs, line 123 \[r3\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100#-Ju60LSUaZe4aQ_JTKyn)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/42ff97acbf75e12ec5f9523113d00795a295b395/src/id/revocation_id_type.rs#L123)):</sup>
Sorry. It is corrected now

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/100)

**Pull request merged**
