### PR TITLE
Maid 1089 delete container

### PR DESCRIPTION
**Pull request by krishnaIndia**
Get version and Delete Container implemented

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/46)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- README.md @ r1
- src/nfs/helper/file_helper.rs @ r1
- src/nfs/io/mod.rs @ r1
- src/nfs/rest/container.rs @ r1

---

<sup>**[src/nfs/rest/container.rs, line 163 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/46#-Jr1swGEQh34RHWxYcS2)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/899652383a0981622a66000639516b40543a5f28/src/nfs/rest/container.rs#L163)):</sup>
routing::NameType ??

---

<sup>**[src/nfs/rest/container.rs, line 168 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/46#-Jr1spjpjNB2ZQ3j02_a)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/899652383a0981622a66000639516b40543a5f28/src/nfs/rest/container.rs#L168)):</sup>
alignment problem

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/46)

**Comment by krishnaIndia** [comment]
Review status: 3 of 4 files reviewed, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/nfs/rest/container.rs, line 168 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/46#-Jr1spjpjNB2ZQ3j02_a)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/899652383a0981622a66000639516b40543a5f28/src/nfs/rest/container.rs#L168)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/46)

**Comment by krishnaIndia** [comment]
Review status: 3 of 4 files reviewed, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/nfs/rest/container.rs, line 163 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/46#-Jr1swGEQh34RHWxYcS2)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/899652383a0981622a66000639516b40543a5f28/src/nfs/rest/container.rs#L163)):</sup>
Imagine drive is using maidsafe_client. They dont have to use the routing crate just for this dependency

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/46)

**Comment by ustulation** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- src/nfs/rest/container.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/46)

**Pull request merged**
