### PR TITLE
Update blob content fix

### PR DESCRIPTION
**Pull request by krishnaIndia**
Updating blob content was not re-writing it completely. Fixed the same

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_client/91)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
<sup>**[examples/rest_api.rs, line 199 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/91#-Jsjck5rEao3HxBfdl1C)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/9e2839f83b547b6e23d12d02d59a0822bf1a26a3/examples/rest_api.rs#L199)):</sup>
trailing spaces

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/91)

**Comment by ustulation** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/91)

**Comment by krishnaIndia** [comment]
<sup>**[examples/rest_api.rs, line 199 \[r2\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/91#-Jsjck5rEao3HxBfdl1C)** ([raw file](https://github.com/maidsafe/maidsafe_client/blob/9e2839f83b547b6e23d12d02d59a0822bf1a26a3/examples/rest_api.rs#L199)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/91)

**Comment by ustulation** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_client/91)

**Pull request merged**
